# Generated by Django 3.1.1 on 2020-09-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200921_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='linkUrl',
        ),
    ]
